#Build settings and parameters

# Support platforms
#PLATFORM=RZG2L-SBC
#PLATFORM=RZG2L-EVK
#PLATFORM=RZV2L-EVK
#PLATFORM=RZV2H-EVK
PLATFORM=RZ-CMN

# List of platforms for the common build (RZ-CMN)
COMMON_PLATFORMS=("RZG2L-SBC" "RZG2L-EVK" "RZV2L-EVK" "RZV2H-EVK" "RZV2H-RDK" "RS-G2L100" "IMDT-V2H-SBC")

# These are the (absolute) input path where the software are located.
KERNEL_DIR=~/workspace/linux-rz
KERNEL_MODULES_OUTPUT_DIR=~/workspace/kernel-modules
UBOOT_DIR=~/workspace/u-boot
ATF_DIR=~/workspace/rz-atf
FLASH_WRITER_DIR=~/workspace/flash-writer

# Support ATF build mode
#ATF_MODE=DEBUG
ATF_MODE=RELEASE
